import type { ViolationCategory } from "./types"

export const koapViolations: Record<string, ViolationCategory> = {
  traffic: {
    name: "Дорожные нарушения (КоАП)",
    items: {
      "5.1": {
        article: "КоАП 5.1",
        description: "Управление ТС без документов",
        fine: 20000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "5.2": {
        article: "КоАП 5.2",
        description: "Непредоставление документов по требованию полиции",
        fine: 30000,
        suspension: 0,
        arrest: 0,
        retraining: true,
        alternatives: [
          {
            name: "Штраф 30000",
            fine: 30000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Лишение прав с возможностью переобучения",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: true,
          },
        ],
      },
      "5.3": {
        article: "КоАП 5.3",
        description: "Управление незарегистрированным ТС или без номеров",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "5.4": {
        article: "КоАП 5.4",
        description: "Управление ТС с тонировкой более 31%",
        fine: 20000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "5.5": {
        article: "КоАП 5.5",
        description: "Управление ТС с технической неисправностью",
        fine: 30000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 10000-30000",
            fine: 10000,
            fineRange: { min: 10000, max: 30000 },
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "5.6": {
        article: "КоАП 5.6",
        description: "Управление мотоциклом без шлема",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 5000",
            fine: 5000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "5.7": {
        article: "КоАП 5.7",
        description: "Нарушение ПДД пешеходами и велосипедистами",
        fine: 15000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 5000-15000",
            fine: 5000,
            fineRange: { min: 5000, max: 15000 },
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "5.8": {
        article: "КоАП 5.8",
        description: "Посадка/высадка пассажиров со стороны проезжей части",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 5000",
            fine: 5000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },

        ],
      },
      "5.9": {
        article: "КоАП 5.9",
        description: "Игнорирование требования об остановке с помощью жезла",
        fine: 20000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "5.10": {
        article: "КоАП 5.10",
        description: "Несоблюдение дорожных знаков или разметки",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "6.1": {
        article: "КоАП 6.1",
        description: "Использование приоритета с маячками без безопасности",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "6.2": {
        article: "КоАП 6.2",
        description: "Нарушение правил использования аварийных сигналов",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 10000",
            fine: 10000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "6.3": {
        article: "КоАП 6.3",
        description: "Нарушение правил использования знака аварийной остановки",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 10000",
            fine: 10000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "6.4": {
        article: "КоАП 6.4",
        description: "Управление ТС с выключенными фарами",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 5000",
            fine: 5000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "6.5": {
        article: "КоАП 6.5",
        description: "Использование звукового сигнала в нарушение ПДД",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 5000",
            fine: 5000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "7.1": {
        article: "КоАП 7.1",
        description: "Проезд на красный сигнал светофора",
        fine: 20000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "7.2": {
        article: "КоАП 7.2",
        description: "Невыполнение требования об остановке перед стоп-линией",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "8.1": {
        article: "КоАП 8.1",
        description: "Маневры без использования поворотников",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 5000",
            fine: 5000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "8.2": {
        article: "КоАП 8.2",
        description: "Непредоставление преимущества при перестроении",
        fine: 20000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "8.3": {
        article: "КоАП 8.3",
        description: "Поворот или разворот из неправильной полосы",
        fine: 20000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "8.4": {
        article: "КоАП 8.4",
        description: "Неправильный поворот, разворот или движение задним ходом",
        fine: 20000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "9.1": {
        article: "КоАП 9.1",
        description: "Движение по полосе, предназначенной для встречного движения",
        fine: 50000,
        suspension: 2,
        suspensionRange: { min: 0, max: 2 },
        arrest: 0,
        retraining: true,
      },
      "9.2": {
        article: "КоАП 9.2",
        description: "Выезд на полосу встречного движения",
        fine: 50000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "9.3": {
        article: "КоАП 9.3",
        description: "Движение по левым полосам при свободных правых",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 5000",
            fine: 5000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "9.4": {
        article: "КоАП 9.4",
        description: "Движение по прерывистым линиям разметки",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 10000",
            fine: 10000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "9.5": {
        article: "КоАП 9.5",
        description: "Движение по разделительным полосам, обочинам, тротуарам",
        fine: 30000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "9.6": {
        article: "КоАП 9.6",
        description: "Несоблюдение дистанции или бокового интервала",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 10000",
            fine: 10000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "10.1": {
        article: "КоАП 10.1",
        description: "Обгон ТС с маячками и звуковым сигналом",
        fine: 20000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "10.2": {
        article: "КоАП 10.2",
        description: "Обгон ТС с цветографическими схемами и маячками",
        fine: 20000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "10.3": {
        article: "КоАП 10.3",
        description: "Обгон в запрещенных случаях",
        fine: 20000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "10.4": {
        article: "КоАП 10.4",
        description: "Препятствование обгону",
        fine: 20000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "11.1": {
        article: "КоАП 11.1",
        description: "Остановка/стоянка на пешеходном переходе",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "11.2": {
        article: "КоАП 11.2",
        description: "Остановка/стоянка в местах остановки маршрутных ТС",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "11.3": {
        article: "КоАП 11.3",
        description: "Остановка/стоянка на трамвайных путях или далее первого ряда",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "11.4": {
        article: "КоАП 11.4",
        description: "Нарушение остановки/стоянки, создающее препятствия",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "11.5": {
        article: "КоАП 11.5",
        description: "Нарушение правил остановки/стоянки",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "12.1": {
        article: "КоАП 12.1",
        description: "Нарушение правил проезда перекрестков без опасности",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 5000",
            fine: 5000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "12.2": {
        article: "КоАП 12.2",
        description: "Нарушение правил проезда перекрестков с опасностью",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "13.1": {
        article: "КоАП 13.1",
        description: "Пересечение ж/д путей в неположенном месте",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 5000",
            fine: 5000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "13.2": {
        article: "КоАП 13.2",
        description: "Выезд на ж/д переезд в запрещенных случаях",
        fine: 20000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "13.3": {
        article: "КоАП 13.3",
        description: "Остановка ближе 5 м от шлагбаума или 10 м от рельса",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 5000",
            fine: 5000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "14.1": {
        article: "КоАП 14.1",
        description: "Движение по автомагистрали со скоростью менее 40 км/ч",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "14.2": {
        article: "КоАП 14.2",
        description: "Движение грузовиков далее второй полосы на автомагистрали",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 5000",
            fine: 5000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "14.3": {
        article: "КоАП 14.3",
        description: "Движение по автомагистрали задним ходом",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "14.4": {
        article: "КоАП 14.4",
        description: "Создание пешеходом помех в жилой зоне",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 5000",
            fine: 5000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "14.5": {
        article: "КоАП 14.5",
        description: "Сквозное движение, учебная езда, стоянка в жилой зоне",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 5000",
            fine: 5000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "14.6": {
        article: "КоАП 14.6",
        description: "Движение в колонне в нарушение ПДД",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 10000",
            fine: 10000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "15.1": {
        article: "КоАП 15.1",
        description: "Непредоставление преимущества ТС с маячками",
        fine: 20000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "15.2": {
        article: "КоАП 15.2",
        description: "Непредоставление преимущества троллейбусам/автобусам",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "15.3": {
        article: "КоАП 15.3",
        description: "Непредоставление преимущества на главной дороге",
        fine: 10000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "15.4": {
        article: "КоАП 15.4",
        description: "Непредоставление преимущества пешеходам/велосипедистам",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Штраф 5000",
            fine: 5000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "16.1": {
        article: "КоАП 16.1",
        description: "Оставление места ДТП",
        fine: 30000,
        suspension: 4,
        suspensionRange: { min: 3, max: 4 },
        arrest: 2,
        retraining: false,
      },
      "16.2": {
        article: "КоАП 16.2",
        description: "Неоказание первой помощи при ДТП",
        fine: 20000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "16.3": {
        article: "КоАП 16.3",
        description: "Невыполнение обязанностей при ДТП",
        fine: 35000,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Штраф 10000-35000",
            fine: 10000,
            fineRange: { min: 10000, max: 35000 },
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "17.1.4": {
        article: "КоАП 17.1.4",
        description: "Управление ТС в состоянии опьянения или передача управления",
        fine: 30000,
        suspension: 1,
        suspensionRange: { min: 0, max: 1 },
        arrest: 0,
        retraining: true,
      },
      "17.1.5": {
        article: "КоАП 17.1.5",
        description: "Невыполнение требования о прохождении освидетельствования",
        fine: 30000,
        suspension: 1,
        suspensionRange: { min: 0, max: 1 },
        arrest: 0,
        retraining: true,
      },
      "17.2": {
        article: "КоАП 17.2",
        description: "Опасное вождение",
        fine: 30000,
        suspension: 2,
        suspensionRange: { min: 0, max: 2 },
        arrest: 0,
        retraining: true,
      },
      "17.5": {
        article: "КоАП 17.5",
        description: "Управление ТС с неуплатой штрафов 50.000–100.000 рублей",
        fine: 50000,
        suspension: 1,
        arrest: 0,
        retraining: false,
      },
      "17.6": {
        article: "КоАП 17.6",
        description: "Управление ТС с неуплатой штрафов более 100.000 рублей",
        fine: 100000,
        suspension: 2,
        arrest: 0,
        retraining: false,
      },
      "18.1": {
        article: "КоАП 18.1",
        description: "Превышение скорости на 10-20 км/ч",
        fine: 0,
        suspension: 0,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "18.2": {
        article: "КоАП 18.2",
        description: "Превышение скорости на 20-40 км/ч",
        fine: 2000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "18.3": {
        article: "КоАП 18.3",
        description: "Превышение скорости на 40-60 км/ч",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "18.4": {
        article: "КоАП 18.4",
        description: "Превышение скорости на 60-80 км/ч",
        fine: 7000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "18.5": {
        article: "КоАП 18.5",
        description: "Превышение скорости на 80+ км/ч",
        fine: 10000,
        suspension: 1,
        arrest: 0,
        retraining: false,
      },
      "19.1": {
        article: "КоАП 19.1",
        description: "Мелкое хулиганство",
        fine: 10000,
        suspension: 0,
        arrest: 1,
        retraining: false,
        alternatives: [
          {
            name: "Арест 10 суток",
            fine: 0,
            suspension: 0,
            arrest: 1,
            retraining: false,
          },
          {
            name: "Штраф 500-10000",
            fine: 500,
            fineRange: { min: 500, max: 10000 },
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "19.2": {
        article: "КоАП 19.2",
        description: "Оскорбление, унижение чести и достоинства",
        fine: 10000,
        suspension: 0,
        arrest: 1,
        retraining: false,
        alternatives: [
          {
            name: "Арест 10 суток",
            fine: 0,
            suspension: 0,
            arrest: 1,
            retraining: false,
          },
          {
            name: "Штраф 500-10000",
            fine: 500,
            fineRange: { min: 500, max: 10000 },
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "19.3": {
        article: "КоАП 19.3",
        description: "Нанесение побоев",
        fine: 20000,
        suspension: 0,
        arrest: 1,
        retraining: false,
        alternatives: [
          {
            name: "Арест 10 суток",
            fine: 0,
            suspension: 0,
            arrest: 1,
            retraining: false,
          },
          {
            name: "Штраф 500-20000",
            fine: 500,
            fineRange: { min: 500, max: 20000 },
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "19.4": {
        article: "КоАП 19.4",
        description: "Потребление алкоголя в общественных местах",
        fine: 5000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "19.5": {
        article: "КоАП 19.5",
        description: "Занятие попрошайничеством",
        fine: 0,
        suspension: 0,
        arrest: 1,
        retraining: false,
        alternatives: [
          {
            name: "Предупреждение",
            fine: 0,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Арест 10 суток",
            fine: 0,
            suspension: 0,
            arrest: 1,
            retraining: false,
          },
        ],
      },
      "19.6": {
        article: "КоАП 19.6",
        description: "Предпринимательская деятельность без регистрации",
        fine: 100000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "19.7": {
        article: "КоАП 19.7",
        description: "Заведомо ложный вызов экстренных служб",
        fine: 20000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
      "19.8": {
        article: "КоАП 19.8",
        description: "Участие в несанкционированном митинге",
        fine: 20000,
        suspension: 0,
        arrest: 1,
        retraining: false,
        alternatives: [
          {
            name: "Арест 10 суток",
            fine: 0,
            suspension: 0,
            arrest: 1,
            retraining: false,
          },
          {
            name: "Штраф 500-20000",
            fine: 500,
            fineRange: { min: 500, max: 20000 },
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "19.9": {
        article: "КоАП 19.9",
        description: "Неповиновение законному распоряжению полиции",
        fine: 20000,
        suspension: 1,
        arrest: 0,
        retraining: false,
        alternatives: [
          {
            name: "Арест до 20 суток",
            fine: 0,
            suspension: 0,
            arrest: 1,
            arrestRange: { min: 1, max: 2 },
            retraining: false,
          },
          {
            name: "Штраф 20000",
            fine: 20000,
            suspension: 0,
            arrest: 0,
            retraining: false,
          },
          {
            name: "Лишение прав на 1 год",
            fine: 0,
            suspension: 1,
            arrest: 0,
            retraining: false,
          },
        ],
      },
      "19.10": {
        article: "КоАП 19.10",
        description: "Клевета",
        fine: 20000,
        suspension: 0,
        arrest: 0,
        retraining: false,
      },
    },
  },
}
