import type { ViolationCategory } from"./types"

export const ukViolations: Record<string, ViolationCategory> = {
 criminal_personal: {
 name:"Преступления против личности (УК)",
 items: {
"4.1": {
 article:"УК 4.1",
 description:"Умышленное причинение вреда здоровью без летального исхода",
 fine: 0,
 suspension: 0,
 arrest: 1,
 retraining: false,
 },
"4.2": {
 article:"УК 4.2",
 description:"Умышленное нанесение особо тяжких телесных повреждений",
 fine: 0,
 suspension: 0,
 arrest: 2,
 retraining: false,
 },
"4.2.1": {
 article:"УК 4.2.1",
 description:"Особо тяжкие телесные повреждения двум или более лицам",
 fine: 0,
 suspension: 0,
 arrest: 4,
 arrestRange: { min: 4, max: 6 },
 retraining: false,
 alternatives: [
 {
 name:"Арест 4-6 лет",
 fine: 0,
 suspension: 0,
 arrest: 4,
 arrestRange: { min: 4, max: 6 },
 retraining: false,
 },
 ],
 },
"4.2.2": {
 article:"УК 4.2.2",
 description:"Особо тяжкие телесные повреждения по неосторожности",
 fine: 0,
 suspension: 0,
 arrest: 2,
 retraining: false,
 alternatives: [
 {
 name:"Арест 1-2 лет",
 fine: 0,
 suspension: 0,
 arrest: 1,
 arrestRange: { min: 1, max: 2 },
 retraining: false,
 },
 ],
 },
"4.3": {
 article:"УК 4.3",
 description:"Угроза нанесения особо тяжких телесных повреждений",
 fine: 0,
 suspension: 0,
 arrest: 1,
 retraining: false,
 },
"4.4": {
 article:"УК 4.4",
 description:"Похищение гражданина или незаконное лишение свободы",
 fine: 0,
 suspension: 0,
 arrest: 4,
 arrestRange: { min: 4, max: 6 },
 retraining: false,
 alternatives: [
 {
 name:"Арест 4-6 лет",
 fine: 0,
 suspension: 0,
 arrest: 4,
 arrestRange: { min: 4, max: 6 },
 retraining: false,
 },
 ],
 },
"4.5": {
 article:"УК 4.5",
 description:"Действия против половой неприкосновенности",
 fine: 0,
 suspension: 0,
 arrest: 3,
 arrestRange: { min: 3, max: 6 },
 retraining: false,
 alternatives: [
 {
 name:"Арест 3-6 лет",
 fine: 0,
 suspension: 0,
 arrest: 3,
 arrestRange: { min: 3, max: 6 },
 retraining: false,
 },
 ],
 },
"4.6": {
 article:"УК 4.6",
 description:"Незаконный сбор сведений о частной жизни",
 fine: 30000,
 suspension: 0,
 arrest: 1,
 retraining: false,
 alternatives: [
 {
 name:"Штраф 30000",
 fine: 30000,
 suspension: 0,
 arrest: 0,
 retraining: false,
 },
 {
 name:"Арест 1 год",
 fine: 0,
 suspension: 0,
 arrest: 1,
 retraining: false,
 },
 ],
 },
 },
 },
 criminal_state: {
 name:"Преступления против государственной власти (УК)",
 items: {
"5.1": {
 article:"УК 5.1",
 description:"Получение взятки должностным лицом",
 fine: 50000,
 suspension: 0,
 arrest: 3,
 retraining: false,
 },
"5.2": {
 article:"УК 5.2",
 description:"Дача взятки должностному лицу",
 fine: 0,
 suspension: 0,
 arrest: 3,
 retraining: false,
 },
"5.3": {
 article:"УК 5.3",
 description:"Посягательство на жизнь и здоровье сотрудника полиции",
 fine: 0,
 suspension: 0,
 arrest: 3,
 arrestRange: { min: 3, max: 6 },
 retraining: false,
 alternatives: [
 {
 name:"Арест 3-6 лет",
 fine: 0,
 suspension: 0,
 arrest: 3,
 arrestRange: { min: 3, max: 6 },
 retraining: false,
 },
 ],
 },
"5.4": {
 article:"УК 5.4",
 description:"Применение насилия в отношении представителя власти",
 fine: 0,
 suspension: 0,
 arrest: 3,
 retraining: false,
 alternatives: [
 {
 name:"Арест 1-3 лет",
 fine: 0,
 suspension: 0,
 arrest: 1,
 arrestRange: { min: 1, max: 3 },
 retraining: false,
 },
 ],
 },
"5.5": {
 article:"УК 5.5",
 description:"Хамство, борзость, дерзость по отношению к сотруднику",
 fine: 0,
 suspension: 0,
 arrest: 0,
 retraining: false,
 alternatives: [
 {
 name:"Штраф 15000",
 fine: 15000,
 suspension: 0,
 arrest: 0,
 retraining: false,
 },
 {
 name:"Арест 1 год",
 fine: 0,
 suspension: 0,
 arrest: 1,
 retraining: false,
 },
 ],
 },
"5.6": {
 article:"УК 5.6",
 description:"Публичное оскорбление представителей власти",
 fine: 0,
 suspension: 0,
 arrest: 0,
 retraining: false,
 alternatives: [
 {
 name:"Штраф 25000",
 fine: 25000,
 suspension: 0,
 arrest: 0,
 retraining: false,
 },
 {
 name:"Арест 2 года",
 fine: 0,
 suspension: 0,
 arrest: 2,
 retraining: false,
 },
 ],
 },
"5.7": {
 article:"УК 5.7",
 description:"Провокационные действия в отношении сотрудников",
 fine: 0,
 suspension: 0,
 arrest: 0,
 retraining: false,
 alternatives: [
 {
 name:"Штраф 50000",
 fine: 50000,
 suspension: 0,
 arrest: 0,
 retraining: false,
 },
 {
 name:"Арест 1-2 года",
 fine: 0,
 suspension: 0,
 arrest: 1,
 arrestRange: { min: 1, max: 2 },
 retraining: false,
 },
 ],
 },
"5.7.1": {
 article:"УК 5.7.1",
 description:"Длительное преследование экипажа полиции",
 fine: 0,
 suspension: 0,
 arrest: 0,
 retraining: false,
 alternatives: [
 {
 name:"Штраф 50000",
 fine: 50000,
 suspension: 0,
 arrest: 0,
 retraining: false,
 },
 {
 name:"Арест 1-2 года",
 fine: 0,
 suspension: 0,
 arrest: 1,
 arrestRange: { min: 1, max: 2 },
 retraining: false,
 },
 ],
 },
"5.8": {
 article:"УК 5.8",
 description:"Неоднократное неповиновение законному распоряжению",
 fine: 0,
 suspension: 0,
 arrest: 2,
 retraining: false,
 },
"5.8.1": {
 article:"УК 5.8.1",
 description:"Уход от полиции с нанесением ущерба имуществу",
 fine: 0,
 suspension: 0,
 arrest: 3,
 retraining: false,
 },
"5.8.2": {
 article:"УК 5.8.2",
 description:"Уход от полиции с причинением телесных повреждений",
 fine: 0,
 suspension: 0,
 arrest: 4,
 retraining: false,
 },
"5.9": {
 article:"УК 5.9",
 description:"Уничтожение имущества государственных организаций",
 fine: 0,
 suspension: 0,
 arrest: 0,
 retraining: false,
 alternatives: [
 {
 name:"Штраф 50000",
 fine: 50000,
 suspension: 0,
 arrest: 0,
 retraining: false,
 },
 {
 name:"Арест 2 года",
 fine: 0,
 suspension: 0,
 arrest: 2,
 retraining: false,
 },
 ],
 },
"5.10": {
 article:"УК 5.10",
 description:"Заведомо ложный донос о совершении преступления",
 fine: 0,
 suspension: 0,
 arrest: 0,
 retraining: false,
 alternatives: [
 {
 name:"Штраф 25000",
 fine: 25000,
 suspension: 0,
 arrest: 0,
 retraining: false,
 },
 {
 name:"Арест 2 года",
 fine: 0,
 suspension: 0,
 arrest: 2,
 retraining: false,
 },
 ],
 },
"5.11": {
 article:"УК 5.11",
 description:"Разглашение секретных данных",
 fine: 0,
 suspension: 0,
 arrest: 3,
 retraining: false,
 alternatives: [
 {
 name:"Арест 1-3 лет",
 fine: 0,
 suspension: 0,
 arrest: 1,
 arrestRange: { min: 1, max: 3 },
 retraining: false,
 },
 ],
 },
"5.12": {
 article:"УК 5.12",
 description:"Представление себя служащим государственной организации",
 fine: 0,
 suspension: 0,
 arrest: 0,
 retraining: false,
 alternatives: [
 {
 name:"Штраф 30000",
 fine: 30000,
 suspension: 0,
 arrest: 0,
 retraining: false,
 },
 {
 name:"Арест 1 год",
 fine: 0,
 suspension: 0,
 arrest: 1,
 retraining: false,
 },
 ],
 },
"5.13": {
 article:"УК 5.13",
 description:"Халатность должностного лица",
 fine: 0,
 suspension: 0,
 arrest: 3,
 retraining: false,
 alternatives: [
 {
 name:"Арест 1-3 лет",
 fine: 0,
 suspension: 0,
 arrest: 1,
 arrestRange: { min: 1, max: 3 },
 retraining: false,
 },
 ],
 },
 },
 },
 criminal_public: {
 name:"Преступления против общественного порядка (УК)",
 items: {
"6.1": {
 article:"УК 6.1",
 description:"Терроризм",
 fine: 0,
 suspension: 0,
 arrest: 6,
 retraining: false,
 alternatives: [
 {
 name:"Арест 1-6 лет",
 fine: 0,
 suspension: 0,
 arrest: 1,
 arrestRange: { min: 1, max: 6 },
 retraining: false,
 },
 ],
 },
"6.2": {
 article:"УК 6.2",
 description:"Заведомо ложное сообщение о готовящихся взрыве",
 fine: 50000,
 suspension: 0,
 arrest: 3,
 retraining: false,
 },
"6.3": {
 article:"УК 6.3",
 description:"Захват или удержание заложника",
 fine: 0,
 suspension: 0,
 arrest: 3,
 retraining: false,
 alternatives: [
 {
 name:"Арест 1-3 лет",
 fine: 0,
 suspension: 0,
 arrest: 1,
 arrestRange: { min: 1, max: 3 },
 retraining: false,
 },
 ],
 },
"6.4": {
 article:"УК 6.4",
 description:"Организация массовых беспорядков",
 fine: 100000,
 suspension: 0,
 arrest: 1,
 retraining: false, 
 alternatives: [
 {
 name:"Арест 1-6 лет + Штраф",
 fine: 100000,
 suspension: 0,
 arrest: 1,
 arrestRange: { min: 1, max: 6 },
 retraining: false,
 },
 ],
 },
"6.5": {
 article:"УК 6.5",
 description:"Создание устойчивой группы для нападений (банды)",
 fine: 0,
 suspension: 0,
 arrest: 1,
 retraining: false,
 alternatives: [
 {
 name:"Арест 1-6 лет",
 fine: 0,
 suspension: 0,
 arrest: 1,
 arrestRange: { min: 1, max: 6 },
 retraining: false,
 },
 ],
 },
"6.6": {
 article:"УК 6.6",
 description:"Вандализм",
 fine: 0,
 suspension: 0,
 arrest: 0,
 retraining: false,
 alternatives: [
 {
 name:"Штраф 10000",
 fine: 10000,
 suspension: 0,
 arrest: 0,
 retraining: false,
 },
 {
 name:"Арест 1 год",
 fine: 0,
 suspension: 0,
 arrest: 1,
 retraining: false,
 },
 ],
 },
"6.7": {
 article:"УК 6.7",
 description:"Незаконное проникновение в жилище",
 fine: 0,
 suspension: 0,
 arrest: 2,
 retraining: false,
 },
"6.8": {
 article:"УК 6.8",
 description:"Самовольное проникновение на охраняемый объект",
 fine: 0,
 suspension: 0,
 arrest: 0,
 retraining: false,
 alternatives: [
 {
 name:"Штраф 10000",
 fine: 10000,
 suspension: 0,
 arrest: 0,
 retraining: false,
 },
 {
 name:"Арест 2 года",
 fine: 0,
 suspension: 0,
 arrest: 2,
 retraining: false,
 },
 ],
 },
"6.9": {
 article:"УК 6.9",
 description:"Незаконное обращение с огнестрельным оружием",
 fine: 20000,
 suspension: 0,
 arrest: 3,
 retraining: false,
 },
"6.10": {
 article:"УК 6.10",
 description:"Незаконные действия с наркотическими средствами",
 fine: 20000,
 suspension: 0,
 arrest: 3,
 retraining: false,
 },
"6.11": {
 article:"УК 6.11",
 description:"Неоказание медицинской помощи",
 fine: 0,
 suspension: 0,
 arrest: 1,
 retraining: false,
 },
"6.12": {
 article:"УК 6.12",
 description:"Попытка срыва мероприятий",
 fine: 0,
 suspension: 0,
 arrest: 3,
 retraining: false,
 },
"6.13": {
 article:"УК 6.13",
 description:"Подделка официального документа",
 fine: 0,
 suspension: 0,
 arrest: 0,
 retraining: false,
 alternatives: [
 {
 name:"Штраф 20000",
 fine: 20000,
 suspension: 0,
 arrest: 0,
 retraining: false,
 },
 {
 name:"Арест 3 года",
 fine: 0,
 suspension: 0,
 arrest: 3,
 retraining: false,
 },
 ],
 },
"6.14": {
 article:"УК 6.14",
 description:"Превышение должностных полномочий",
 fine: 0,
 suspension: 0,
 arrest: 0,
 retraining: false,
 alternatives: [
 {
 name:"Штраф 500-50000",
 fine: 500,
 fineRange: { min: 500, max: 50000 },
 suspension: 0,
 arrest: 0,
 retraining: false,
 },
 {
 name:"Арест 1-3 года",
 fine: 0,
 suspension: 0,
 arrest: 3,
 arrestRange: { min: 1, max: 3 },
 retraining: false,
 },
 ],
 },
 },
 },
 criminal_economic: {
 name:"Экономические преступления (УК)",
 items: {
"7.1": {
 article:"УК 7.1",
 description:"Мошенничество",
 fine: 0,
 suspension: 0,
 arrest: 0,
 retraining: false,
 alternatives: [
 {
 name:"Штраф 50000 и возмещение ущерба",
 fine: 50000,
 suspension: 0,
 arrest: 0,
 retraining: false,
 },
 {
 name:"Арест 3 года",
 fine: 0,
 suspension: 0,
 arrest: 3,
 retraining: false,
 },
 ],
 },
"7.2": {
 article:"УК 7.2",
 description:"Грабеж или кража чужого имущества",
 fine: 0,
 suspension: 0,
 arrest: 2,
 retraining: false,
 },
"7.3": {
 article:"УК 7.3",
 description:"Вымогательство",
 fine: 0,
 suspension: 0,
 arrest: 3,
 retraining: false,
 },
"7.4": {
 article:"УК 7.4",
 description:"Умышленное уничтожение чужого имущества",
 fine: 0,
 suspension: 0,
 arrest: 0,
 retraining: false,
 alternatives: [
 {
 name:"Штраф 50000 и возмещение ущерба",
 fine: 50000,
 suspension: 0,
 arrest: 0,
 retraining: false,
 },
 {
 name:"Арест 2 года",
 fine: 0,
 suspension: 0,
 arrest: 2,
 retraining: false,
 },
 ],
 },
"7.5": {
 article:"УК 7.5",
 description:"Организация азартных игр в общественных местах",
 fine: 0,
 suspension: 0,
 arrest: 0,
 retraining: false,
 alternatives: [
 {
 name:"Штраф 50000",
 fine: 50000,
 suspension: 0,
 arrest: 0,
 retraining: false,
 },
 {
 name:"Арест 2 года",
 fine: 0,
 suspension: 0,
 arrest: 2,
 retraining: false,
 },
 ],
 },
 },
 },
}
